import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding STEMVERSE...');
  const ap = await bcrypt.hash('admin123', 12);
  await prisma.user.upsert({ where: { email: 'admin@stemverse.io' }, update: {}, create: { name: 'Admin', email: 'admin@stemverse.io', password: ap, role: 'ADMIN', xp: 9999, level: 50 } });
  const sp = await bcrypt.hash('student123', 12);
  await prisma.user.upsert({ where: { email: 'student@stemverse.io' }, update: {}, create: { name: 'Demo Student', email: 'student@stemverse.io', password: sp, role: 'STUDENT', xp: 150, level: 1 } });
  const tp = await bcrypt.hash('teacher123', 12);
  await prisma.user.upsert({ where: { email: 'teacher@stemverse.io' }, update: {}, create: { name: 'Ms. Karimova', email: 'teacher@stemverse.io', password: tp, role: 'TEACHER', xp: 0, level: 1 } });
  for (let i = 1; i <= 30; i++) {
    await prisma.activationCode.upsert({ where: { code: 'SV-DEMO-' + String(i).padStart(3, '0') }, update: {}, create: { code: 'SV-DEMO-' + String(i).padStart(3, '0') } });
  }
  const achievements = [
    { id: 'first_circuit', title: 'Birinchi Sxema', description: 'Birinchi darsni tugating', icon: '🔌', xpReward: 50, condition: { type: 'first_lesson' } },
    { id: 'led_master', title: 'LED Ustasi', description: '3 ta LED darsini tugating', icon: '💡', xpReward: 100, condition: { type: 'lessons_completed', count: 3 } },
    { id: 'kit_activated', title: 'Kit Faollashtirildi', description: 'Activate your STEMVERSE kit', icon: '🎮', xpReward: 50, condition: { type: 'kit_activated' } },
    { id: 'sensor_expert', title: 'Sensor Mutaxassisi', description: 'Complete 5 sensor lessons', icon: '📡', xpReward: 150, condition: { type: 'lessons_completed', count: 5 } },
    { id: 'speed_demon', title: 'Tezlik Demon', description: 'Complete Speed Runner', icon: '🏃', xpReward: 100, condition: { type: 'lessons_completed', count: 6 } },
    { id: 'music_maestro', title: 'Musiqa Ustasi', description: 'Play with sound components', icon: '🎵', xpReward: 100, condition: { type: 'lessons_completed', count: 7 } },
    { id: 'robot_builder', title: 'Robot Quruvchi', description: 'Complete Robot Arm lesson', icon: '🦾', xpReward: 150, condition: { type: 'lessons_completed', count: 11 } },
    { id: 'xp_collector', title: "XP Yig'uvchi", description: 'Earn 500 XP', icon: '🏆', xpReward: 250, condition: { type: 'xp_reached', xp: 500 } },
    { id: 'engineer_5', title: 'Muhandis 5-Daraja', description: 'Reach level 5', icon: '⭐', xpReward: 200, condition: { type: 'xp_reached', xp: 1000 } },
    { id: 'master_engineer', title: 'Bosh Muhandis', description: 'Complete all 20 lessons', icon: '👑', xpReward: 500, condition: { type: 'lessons_completed', count: 20 } },
  ];
  for (const a of achievements) { await prisma.achievement.upsert({ where: { id: a.id }, update: {}, create: a }); }

  // ===== 20 LESSONS WITH 20 UNIQUE GAMES =====
  console.log('Creating 20 lessons with 20 games...');
  const lessons = [
    // === LEVEL 1: BASICS (Arduino Uno) ===
    { id: 'lesson_1', title: "LEDni Yondirish", description: "Arduino bilan LED yondirishni organing — ilk sxemangiz!", level: 1, order: 1, components: ['Arduino Uno', 'LED', '220Ω Resistor', 'Breadboard', 'Jumper wires'], codeExample: 'void setup() { pinMode(13, OUTPUT); }\nvoid loop() { digitalWrite(13, HIGH); delay(1000); digitalWrite(13, LOW); delay(1000); }', gameConfig: { gameType: 'energy_city', title: "Energy City - Chiroqlar Yonadi!" }, winCondition: { type: 'led_blink_count', count: 5 }, xpReward: 50, published: true },
    { id: 'lesson_2', title: "Svetafor Boshqaruvi", description: "3 xil LED bilan svetafor yasang va transport oqimini boshqaring!", level: 1, order: 2, components: ['Arduino Uno', '3 LEDs (Red/Yellow/Green)', '3x 220Ω Resistors', 'Push button', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ pinMode(13,OUTPUT); pinMode(12,OUTPUT); pinMode(11,OUTPUT); pinMode(2,INPUT); Serial.begin(9600); }\nvoid loop(){ int b=digitalRead(2); if(b==1){ Serial.println("BTN:1"); } digitalWrite(13,HIGH); delay(3000); digitalWrite(13,LOW); digitalWrite(12,HIGH); delay(1000); digitalWrite(12,LOW); digitalWrite(11,HIGH); delay(3000); digitalWrite(11,LOW); }', gameConfig: { gameType: 'traffic_light', title: "Svetafor Challenge" }, winCondition: { type: 'cycles_completed', count: 10 }, xpReward: 75, published: true },
    { id: 'lesson_3', title: "RGB Ranglar Sehri", description: "3 potensiometr va RGB LED yordamida ranglarni aralashtiring!", level: 1, order: 3, components: ['Arduino Uno', 'RGB LED', '3x 220Ω Resistors', '3x Potentiometers 10kΩ', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ pinMode(9,OUTPUT); pinMode(10,OUTPUT); pinMode(11,OUTPUT); Serial.begin(9600); }\nvoid loop(){ int r=analogRead(A0)/4; int g=analogRead(A1)/4; int b=analogRead(A2)/4; analogWrite(9,r); analogWrite(10,g); analogWrite(11,b); Serial.print("R:"); Serial.print(r); Serial.print(" G:"); Serial.print(g); Serial.print(" B:"); Serial.println(b); delay(100); }', gameConfig: { gameType: 'color_mixer', title: "Ranglar Sehri" }, winCondition: { type: 'power_reached', value: 900 }, xpReward: 100, published: true },
    { id: 'lesson_4', title: "Yoruglik Shousi", description: "LEDlar va tugma yordamida ajoyib yoruglik patternlarini yarating!", level: 1, order: 4, components: ['Arduino Uno', '4 LEDs', '4x 220Ω Resistors', 'Push button', 'Breadboard', 'Jumper wires'], codeExample: 'int leds[]={13,12,11,10};\nvoid setup(){ for(int i=0;i<4;i++) pinMode(leds[i],OUTPUT); pinMode(2,INPUT); Serial.begin(9600); }\nvoid loop(){ for(int i=0;i<4;i++){ digitalWrite(leds[i],HIGH); delay(200); digitalWrite(leds[i],LOW); } Serial.println("BTN:"+String(digitalRead(2))); }', gameConfig: { gameType: 'light_show', title: "Yoruglik Shousi" }, winCondition: { type: 'dances_completed', count: 3 }, xpReward: 100, published: true },
    { id: 'lesson_5', title: "Maxfiy Kodli Eshik", description: "Tugma va LED yordamida maxfiy kodli qulf yarating!", level: 1, order: 5, components: ['Arduino Uno', 'Push button', 'LED', 'Buzzer', '220Ω Resistor', 'Breadboard', 'Jumper wires'], codeExample: 'int code[]={1,0,1,1,0}; int pos=0;\nvoid setup(){ pinMode(2,INPUT); pinMode(13,OUTPUT); pinMode(6,OUTPUT); Serial.begin(9600); }\nvoid loop(){ int b=digitalRead(2); if(b==1){ Serial.println("BTN:1"); if(code[pos]==1) pos++; else pos=0; if(pos==5){ digitalWrite(13,HIGH); tone(6,1000,500); delay(500); digitalWrite(13,LOW); pos=0; } delay(200); } }', gameConfig: { gameType: 'secret_code', title: "Maxfiy Kodli Eshik" }, winCondition: { type: 'dances_completed', count: 1 }, xpReward: 125, published: true },

    // === LEVEL 2: SENSORS (Arduino Uno) ===
    { id: 'lesson_6', title: "Tezlik Poygasi", description: "Potensiometr bilan yuguruvchini boshqaring! Tugma bilan sakrang!", level: 2, order: 6, components: ['Arduino Uno', 'Potentiometer 10kΩ', 'Push button', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ pinMode(2,INPUT); Serial.begin(9600); }\nvoid loop(){ int pot=analogRead(A0); int btn=digitalRead(2); Serial.print("POT:"); Serial.println(pot); if(btn==1){ Serial.println("BTN:1"); delay(200); } delay(50); }', gameConfig: { gameType: 'speed_runner', title: "Tezlik Poygasi - Cheksiz Yugurish" }, winCondition: { type: 'distance_reached', value: 1000 }, xpReward: 150, published: true },
    { id: 'lesson_7', title: "Yoruglik Theremini", description: "LDR sensor yordamida yoruglik bilan musiqa yarating!", level: 2, order: 7, components: ['Arduino Uno', 'LDR (Light Sensor)', '10kΩ Resistor', 'Buzzer', 'LED', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ Serial.begin(9600); pinMode(6,OUTPUT); pinMode(13,OUTPUT); }\nvoid loop(){ int light=analogRead(A0); int freq=map(light,0,1023,100,2000); tone(6,freq); analogWrite(13,light/4); Serial.print("LDR:"); Serial.println(light); delay(100); }', gameConfig: { gameType: 'light_theremin', title: "Yoruglik Theremini" }, winCondition: { type: 'power_reached', value: 800 }, xpReward: 150, published: true },
    { id: 'lesson_8', title: "Harorat Bogi", description: "Haroratni kuzating va virtual bogingizni soglom saqlang!", level: 2, order: 8, components: ['Arduino Uno', 'LM35 Temperature Sensor', '3 LEDs', '3x 220Ω Resistors', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ Serial.begin(9600); pinMode(13,OUTPUT); pinMode(12,OUTPUT); pinMode(11,OUTPUT); }\nvoid loop(){ int val=analogRead(A0); float mv=val*5.0/1024; float temp=mv*100; Serial.print("TEMP:"); Serial.println((int)temp); if(temp<20){ digitalWrite(13,HIGH); digitalWrite(12,LOW); digitalWrite(11,LOW); } else if(temp<30){ digitalWrite(13,LOW); digitalWrite(12,HIGH); digitalWrite(11,LOW); } else{ digitalWrite(13,LOW); digitalWrite(12,LOW); digitalWrite(11,HIGH); } delay(500); }', gameConfig: { gameType: 'temp_garden', title: "Harorat Bogi" }, winCondition: { type: 'time_alive', value: 30000 }, xpReward: 175, published: true },
    { id: 'lesson_9', title: "Masofa Radari", description: "Ultrasonic sensor yordamida masofani aniqlang va olchang!", level: 2, order: 9, components: ['Arduino Uno', 'HC-SR04 Ultrasonic Sensor', '4 LEDs', '4x 220Ω Resistors', 'Breadboard', 'Jumper wires'], codeExample: 'int trig=9, echo=8;\nvoid setup(){ pinMode(trig,OUTPUT); pinMode(echo,INPUT); Serial.begin(9600); pinMode(13,OUTPUT); pinMode(12,OUTPUT); pinMode(11,OUTPUT); pinMode(10,OUTPUT); }\nvoid loop(){ digitalWrite(trig,LOW); delayMicroseconds(2); digitalWrite(trig,HIGH); delayMicroseconds(10); digitalWrite(trig,LOW); int dist=pulseIn(echo,HIGH)/58; Serial.print("DIST:"); Serial.println(dist); int bars=map(dist,0,100,4,0); for(int i=0;i<4;i++) digitalWrite(13-i,bars>i?HIGH:LOW); delay(200); }', gameConfig: { gameType: 'distance_radar', title: "Masofa Radari" }, winCondition: { type: 'power_reached', value: 950 }, xpReward: 175, published: true },
    { id: 'lesson_10', title: "Reaksiya Chempioni", description: "Ikki o'yinchili reaksiya o'yini! Kim birinchi bosadi?", level: 2, order: 10, components: ['Arduino Uno', '2 Push buttons', 'LED', 'Buzzer', '220Ω Resistor', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ pinMode(2,INPUT); pinMode(3,INPUT); pinMode(13,OUTPUT); pinMode(6,OUTPUT); Serial.begin(9600); randomSeed(analogRead(0)); }\nvoid loop(){ delay(random(2000,5000)); digitalWrite(13,HIGH); tone(6,2000,100); long start=millis(); int winner=0; while(millis()-start<2000){ if(digitalRead(2)==1){ winner=1; break; } if(digitalRead(3)==1){ winner=2; break; } } digitalWrite(13,LOW); Serial.print("BTN:"); Serial.println(winner); delay(1000); }', gameConfig: { gameType: 'reaction_champion', title: "Reaksiya Chempioni" }, winCondition: { type: 'cycles_completed', count: 5 }, xpReward: 200, published: true },

    // === LEVEL 3: COMBINATIONS (Arduino Uno/Nano) ===
    { id: 'lesson_11', title: "Robot Qol Boshqaruvi", description: "Servo motorli robot qolini potensiometrlar bilan boshqaring!", level: 3, order: 11, components: ['Arduino Uno', 'Servo Motor', 'Potentiometer 10kΩ', 'Ultrasonic Sensor', 'Push button', 'Breadboard', 'Jumper wires'], codeExample: '#include <Servo.h>\nServo base;\nvoid setup(){ base.attach(9); pinMode(2,INPUT); Serial.begin(9600); }\nvoid loop(){ int pot=analogRead(A0); int ang=map(pot,0,1023,0,180); base.write(ang); Serial.print("POT:"); Serial.println(pot); int btn=digitalRead(2); if(btn==1){ Serial.println("BTN:1"); delay(300); } delay(50); }', gameConfig: { gameType: 'robot_arm', title: "Robot Qol Challenge" }, winCondition: { type: 'targets_collected', count: 3 }, xpReward: 225, published: true },
    { id: 'lesson_12', title: "Piano Chalish", description: "4 tugmali pianino yasang va kuy chaling!", level: 3, order: 12, components: ['Arduino Uno', '4 Push buttons', 'Buzzer', '4x 10kΩ Resistors', 'Breadboard', 'Jumper wires'], codeExample: 'int notes[]={262,294,330,349};\nvoid setup(){ for(int i=2;i<=5;i++) pinMode(i,INPUT_PULLUP); pinMode(6,OUTPUT); Serial.begin(9600); }\nvoid loop(){ for(int i=0;i<4;i++){ if(digitalRead(i+2)==LOW){ tone(6,notes[i]); Serial.print("BTN:"); Serial.println(i+1); delay(200); noTone(6); } } }', gameConfig: { gameType: 'piano_player', title: "Piano Chalish" }, winCondition: { type: 'dances_completed', count: 2 }, xpReward: 225, published: true },
    { id: 'lesson_13', title: "Aqlli Issiqxona", description: "Harorat va tuproq namligini kuzatib, osimliklarni soglom saglang!", level: 3, order: 13, components: ['Arduino Uno', 'LM35 Temp Sensor', 'Soil Moisture Sensor', 'LED', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ Serial.begin(9600); pinMode(13,OUTPUT); }\nvoid loop(){ int temp=analogRead(A0)*0.488; int moist=analogRead(A1); Serial.print("TEMP:"); Serial.println(temp); Serial.print("MOIST:"); Serial.println(moist); if(temp>28||moist<300){ digitalWrite(13,HIGH); }else{ digitalWrite(13,LOW); } delay(1000); }', gameConfig: { gameType: 'temp_garden', title: "Aqlli Issiqxona" }, winCondition: { type: 'time_alive', value: 60000 }, xpReward: 250, published: true },
    { id: 'lesson_14', title: "Parking Yordamchisi", description: "Ultrasonic sensor yordamida mashinani park qiling!", level: 3, order: 14, components: ['Arduino Uno', 'HC-SR04 Ultrasonic', 'LED', 'Buzzer', 'Breadboard', 'Jumper wires'], codeExample: 'int trig=9, echo=8;\nvoid setup(){ pinMode(trig,OUTPUT); pinMode(echo,INPUT); pinMode(13,OUTPUT); pinMode(6,OUTPUT); Serial.begin(9600); }\nvoid loop(){ digitalWrite(trig,LOW); delayMicroseconds(2); digitalWrite(trig,HIGH); delayMicroseconds(10); digitalWrite(trig,LOW); int dist=pulseIn(echo,HIGH)/58; Serial.print("DIST:"); Serial.println(dist); if(dist<20){ digitalWrite(13,HIGH); tone(6,1000+dist*10); }else{ digitalWrite(13,LOW); noTone(6); } delay(100); }', gameConfig: { gameType: 'parking_assistant', title: "Parking Yordamchisi" }, winCondition: { type: 'cycles_completed', count: 5 }, xpReward: 250, published: true },
    { id: 'lesson_15', title: "Meteor Hujumidan Himoya", description: "Bazangizni meteorlardan himoya qiling!", level: 3, order: 15, components: ['Arduino Uno', 'Push button', 'Potentiometer', 'Buzzer', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ pinMode(2,INPUT); pinMode(6,OUTPUT); Serial.begin(9600); }\nvoid loop(){ int pot=analogRead(A0); int btn=digitalRead(2); Serial.print("POT:"); Serial.println(pot); if(btn==1){ Serial.println("BTN:1"); tone(6,2000,100); } delay(50); }', gameConfig: { gameType: 'obstacle_course', title: "Meteor Hujumidan Himoya" }, winCondition: { type: 'distance_reached', value: 500 }, xpReward: 275, published: true },

    // === LEVEL 4: ADVANCED + IoT (ESP8266/ESP32 + Firebase) ===
    { id: 'lesson_16', title: "Xavfsizlik Tizimi", description: "Harakatga asoslangan xavfsizlik tizimini yarating!", level: 4, order: 16, components: ['Arduino Uno', 'PIR Motion Sensor', 'Buzzer', 'LED', 'Push button', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ pinMode(2,INPUT); pinMode(13,OUTPUT); pinMode(6,OUTPUT); Serial.begin(9600); }\nvoid loop(){ int motion=digitalRead(2); Serial.print("PIR:"); Serial.println(motion); if(motion==1){ digitalWrite(13,HIGH); tone(6,1000); delay(500); noTone(6); }else{ digitalWrite(13,LOW); } delay(200); }', gameConfig: { gameType: 'motion_alarm', title: "Xavfsizlik Tizimi" }, winCondition: { type: 'cycles_completed', count: 10 }, xpReward: 300, published: true },
    { id: 'lesson_17', title: "Musiqa Vizualizatori", description: "Musiqangizni korish! LEDlar yordamida chastotalarni boshqaring!", level: 4, order: 17, components: ['Arduino Uno', 'Potentiometer', '4 LEDs', 'Buzzer', '4x 220Ω', 'Breadboard', 'Jumper wires'], codeExample: 'void setup(){ for(int i=9;i<=12;i++) pinMode(i,OUTPUT); pinMode(6,OUTPUT); Serial.begin(9600); }\nvoid loop(){ int pot=analogRead(A0); int freq=map(pot,0,1023,100,2000); int bars=map(pot,0,1023,0,4); tone(6,freq); for(int i=0;i<4;i++) digitalWrite(9+i,bars>i?HIGH:LOW); Serial.print("POT:"); Serial.println(pot); delay(100); }', gameConfig: { gameType: 'music_visualizer', title: "Musiqa Vizualizatori" }, winCondition: { type: 'dances_completed', count: 3 }, xpReward: 300, published: true },
    { id: 'lesson_18', title: "IoT Dashboard", description: "ESP8266 WiFi malumotlari — sensor malumotlarini bulutga yuboring!", level: 4, order: 18, components: ['ESP8266 NodeMCU', 'Potentiometer 10kΩ', 'Push button', 'HC-SR04 Ultrasonic', 'LM35 Temp Sensor', 'Breadboard', 'Jumper wires', 'WiFi Router'], codeExample: '#include <ESP8266WiFi.h>\n#include <FirebaseESP8266.h>\n#define FIREBASE_HOST "stemverse-iot.firebaseio.com"\n#define FIREBASE_AUTH "your_secret"\n#define WIFI_SSID "STEMVERSE"\n#define WIFI_PASS "stemverse123"\nFirebaseData fbdo;\nvoid setup(){ Serial.begin(9600); WiFi.begin(WIFI_SSID,WIFI_PASS); Firebase.begin(FIREBASE_HOST,FIREBASE_AUTH); }\nvoid loop(){ int pot=analogRead(A0); Firebase.setInt(fbdo,"sensors/pot",pot); Serial.print("POT:"); Serial.println(pot); delay(1000); }', gameConfig: { gameType: 'iot_dashboard', title: "IoT Dashboard" }, winCondition: { type: 'targets_collected', count: 5 }, xpReward: 400, published: true },
    { id: 'lesson_19', title: "Masofaviy Sensor Stansiyasi", description: "ESP32 global sensor stansiyasi — Firebase real-time malumot sinxronizatsiyasi!", level: 4, order: 19, components: ['ESP32 Dev Board', 'LM35 Temp Sensor', 'LDR Light Sensor', 'HC-SR04 Ultrasonic', 'LED', 'Buzzer', 'Breadboard', 'Jumper wires', 'WiFi Router'], codeExample: '#include <WiFi.h>\n#include <FirebaseESP32.h>\n#define FIREBASE_HOST "stemverse-iot.firebaseio.com"\n#define FIREBASE_AUTH "your_secret"\nFirebaseData fbdo;\nvoid setup(){ Serial.begin(9600); WiFi.begin("STEMVERSE","stemverse123"); Firebase.begin(FIREBASE_HOST,FIREBASE_AUTH); }\nvoid loop(){ int temp=analogRead(A0)*0.488; int light=analogRead(A1); Firebase.setInt(fbdo,"sensors/temp",temp); Firebase.setInt(fbdo,"sensors/light",light); Serial.print("TEMP:"); Serial.print(temp); Serial.print(" LDR:"); Serial.println(light); delay(2000); }', gameConfig: { gameType: 'remote_sensor', title: "Masofaviy Sensor Stansiyasi" }, winCondition: { type: 'time_alive', value: 60000 }, xpReward: 450, published: true },
    { id: 'lesson_20', title: "Aqlli Uy Boshqaruvi", description: "FINAL BOSS: ESP32 aqlli uyni Firebase orqali boshqaring!", level: 4, order: 20, components: ['ESP32 Dev Board', 'LED', 'Push button', 'Potentiometer 10kΩ', 'LM35 Temp Sensor', 'HC-SR04 Ultrasonic', 'LDR', 'Buzzer', 'Servo Motor', 'Breadboard', 'Jumper wires', 'WiFi Router', 'Firebase Account'], codeExample: '#include <WiFi.h>\n#include <FirebaseESP32.h>\nFirebaseData fbdo;\nvoid setup(){ Serial.begin(9600); WiFi.begin("STEMVERSE","stemverse123"); Firebase.begin("stemverse-iot.firebaseio.com","your_secret"); pinMode(2,INPUT); pinMode(13,OUTPUT); }\nvoid loop(){ int pot=analogRead(A0); int btn=digitalRead(2); int temp=analogRead(A1)*0.488; Firebase.setInt(fbdo,"home/pot",pot); Firebase.setInt(fbdo,"home/btn",btn); Firebase.setInt(fbdo,"home/temp",temp); if(Firebase.getInt(fbdo,"home/led")) digitalWrite(13,fbdo.intData()); Serial.print("POT:"); Serial.print(pot); Serial.print(" BTN:"); Serial.print(btn); Serial.print(" TEMP:"); Serial.println(temp); delay(500); }', gameConfig: { gameType: 'smart_home', title: "Aqlli Uy Boshqaruvi" }, winCondition: { type: 'targets_collected', count: 5 }, xpReward: 500, published: true },
  ];
  for (const l of lessons) { await prisma.lesson.upsert({ where: { id: l.id }, update: {}, create: l }); }
  console.log('\\n🎉 STEMVERSE seeding complete!');
  console.log('20 lessons created across 4 levels');
  console.log('10 achievements (including Master Engineer)');
  console.log('Arduino: Lessons 1-17 | ESP8266: Lesson 18 | ESP32: Lessons 19-20');
  console.log('Games: energy_city, traffic_light, color_mixer, light_show, speed_runner,');
  console.log('  light_theremin, temp_garden, distance_radar, reaction_champion, robot_arm,');
  console.log('  piano_player, parking_assistant, motion_alarm, music_visualizer, maze_navigator,');
  console.log('  weather_station, obstacle_course, iot_dashboard, remote_sensor, smart_home');
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());